POST http://localhost:4600/user/register
Content-Type: application/json

{
    "Username":"mahubali",
    "Email":"Mahubali123@gmail.com",
    "PasswordHash":"12345678"
}


###User login
POST http://localhost:4600/user/login
Content-Type: application/json

{
    "Email":"dawud@gmail.com",
    "PasswordHash":"12345678"
}



###Update user Bio

PUT http://localhost:4600/user/update/1
Content-Type: application/json

{
    "UserBio":"mambo ni mengi",
    "UserProfile":"https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/33/505623/1.jpg",
    "UserBackgroundImage":"https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/33/505623/1.jpg"
}


###follow actions
###follow
POST http://localhost:4600/followActions/follow
Content-Type: application/json

{
    "UserID":"2",
    "FollowerUserID":"1"
}


###unfollow
POST http://localhost:4600/followActions/unfollow
Content-Type: application/json

{
    "UserID":"2",
    "FollowerUserID":"1"
}

