POST http://localhost:4600/user/register
Content-Type: application/json

{
    "Username":"mahubali",
    "Email":"Mahubali123@gmail.com",
    "PasswordHash":"12345678"
}


###User login
POST http://localhost:4600/user/login
Content-Type: application/json

{
    "Email":"dawud@gmail.com",
    "PasswordHash":"12345678"
}



###Update user Bio

PUT http://localhost:4600/user/update/1
Content-Type: application/json

{
    "UserBio":"mambo ni mengi",
    "UserProfile":"https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/33/505623/1.jpg",
    "UserBackgroundImage":"https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/33/505623/1.jpg"
}


###follow actions
###follow
POST http://localhost:4600/followActions/follow
Content-Type: application/json

{
    "UserID":"2",
    "FollowerUserID":"1"
}


###unfollow
POST http://localhost:4600/followActions/unfollow
Content-Type: application/json

{
    "UserID":"2",
    "FollowerUserID":"1"
}


###view followings
GET http://localhost:4600/followActions/viewfollowing/2


###view followers
GET http://localhost:4600/followActions/viewfollowers/1 



###create post
POST http://localhost:4600/postActions/createPost
Content-Type: application/json

{
    "UserID":"1",
    "PostContent":"Supporting Arsenal is a not do thing"
}


###Delete Post
DELETE http://localhost:4600/postActions/deletePost/1


###view all posts
GET http://localhost:4600/postActions/viewAllPosts
Content-Type: application/json

###create comment
POST http://localhost:4600/commentActions/createComment
Content-Type: application/json

{
    "UserID":"2",
    "PostID":"2",
    "CommentText":"Thats why i support manchester City"
}


###delete comment
DELETE http://localhost:4600/commentActions/deleteComment/3 


###update comment
PUT http://localhost:4600/commentActions/updateComment/4
Content-Type: application/json

{
    "CommentText":"Poor Club thta is a club that need support"
}


###GET ALL COMMENTS
GET http://localhost:4600/commentActions/viewAllComments
Content-Type: application/json