ALTER TABLE Users
ADD CONSTRAINT PK_Users_UserID PRIMARY KEY (UserID);

ALTER TABLE Users
ADD CONSTRAINT UQ_Users_Username UNIQUE (Username);

ALTER TABLE Users
ADD CONSTRAINT UQ_Users_Email UNIQUE (Email);
